trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*
jobs:
- template: azure/job_template.yml
  parameters:
    name: 'Windows'
    vmImage: 'VS2017-Win2016'
    robotPrefix: 'PATH=~/bin:${PATH}'
    coverage: 'false'
    timeout: 30

